### ISSUE TITLE
[Bug]: check_data_orientation key-error for data

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#199]
### What happened?

One of several occurrences of issues when scanning dandiset 000065

[000065.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543182/000065.txt)

### Traceback

```shell
0.0.0  sub-Kibbles/sub-Kibbles_behavior+ecephys.nwb and 2 other files: 'None' object with name 'None'
         Message: Traceback (most recent call last):
  File "/home/jovyan/GitHub/nwbinspector/nwbinspector/nwbinspector.py", line 503, in run_checks
    output = check_function(nwbfile_object)
  File "/home/jovyan/GitHub/nwbinspector/nwbinspector/register_checks.py", line 127, in auto_parse_some_output
    output = check_function(*args, **kwargs)
  File "/home/jovyan/GitHub/nwbinspector/nwbinspector/checks/time_series.py", line 37, in check_data_orientation
    if time_series.data is not None and any(np.array(time_series.data.shape[1:]) > time_series.data.shape[0]):
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/pynwb/base.py", line 233, in data
    if isinstance(self.fields['data'], TimeSeries):
KeyError: 'data'
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.9

### Usage

Library (Python code)

### Were you streaming with ROS3?

Yes

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
Considering this a part of #198
