### ISSUE TITLE
[Bug]: Explicit example of ElectrodeTable construction error

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#200]
### What happened?

Mentioned as a part of #197, but here's an explicit case of it found from inspecting dandiset 000165.

[000165.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/8543204/000165.txt)

### Traceback

```shell
0.0.0  sub-Salt/sub-Salt_ses-Salt05-LinearTrack_behavior+ecephys.nwb: 'None' object with name 'None'
         Message: Traceback (most recent call last):
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1244, in construct
    obj = self.__new_container__(cls, builder.source, parent, builder.attributes.get(self.__spec.id_key()),
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1254, in __new_container__
    obj.__init__(**kwargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/common/table.py", line 412, in __init__
    tmp.extend(indices[name])
KeyError: 'reference'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jovyan/GitHub/nwbinspector/nwbinspector/nwbinspector.py", line 476, in inspect_nwb
    nwbfile = io.read()
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/backends/hdf5/h5tools.py", line 498, in read
    return call_docval_func(super().read, kwargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 424, in call_docval_func
    return func(*fargs, **fkwargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/backends/io.py", line 41, in read
    container = self.__manager.construct(f_builder)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 280, in construct
    result = self.__type_map.construct(builder, self, None)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1194, in __get_sub_builders
    ret.update(self.__get_subspec_values(sub_builder, subspec, manager))
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1186, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1186, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1143, in __get_subspec_values
    self.__get_sub_builders(groups, spec.groups, manager, ret)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1186, in __get_sub_builders
    sub_builder = self.__flatten(sub_builder, subspec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in __flatten
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1199, in <listcomp>
    tmp = [manager.construct(b) for b in sub_builder]
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1144, in __get_subspec_values
    self.__get_sub_builders(datasets, spec.datasets, manager, ret)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1196, in __get_sub_builders
    ret[subspec] = manager.construct(sub_builder)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1214, in construct
    subspecs = self.__get_subspec_values(builder, self.spec, manager)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1109, in __get_subspec_values
    ret[attr_spec] = manager.construct(attr_val)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 276, in construct
    result = self.__type_map.construct(builder, self, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/manager.py", line 794, in construct
    return obj_mapper.construct(builder, build_manager, parent)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/utils.py", line 583, in func_call
    return func(args[0], **pargs)
  File "/home/jovyan/my-conda-envs/nwbinspector/lib/python3.10/site-packages/hdmf/build/objectmapper.py", line 1248, in construct
    raise ConstructError(builder, msg) from ex
hdmf.build.errors.ConstructError: (root/general/extracellular_ephys/electrodes GroupBuilder {'attributes': {'colnames': array(['rel_x', 'rel_y', 'rel_z', 'location', 'reference', 'group',
       'group_name', 'label', 'x', 'y', 'z', 'imp', 'filtering'],
      dtype=object), 'description': 'all electrodes', 'namespace': 'hdmf-common', 'neurodata_type': 'DynamicTable', 'object_id': 'f76d9069-df22-4ce6-be22-75b29c69351c'}, 'groups': {}, 'datasets': {'filtering': root/general/extracellular_ephys/electrodes/filtering DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '6a94d3ac-020f-42cf-9ae5-9b79b1ca1406'}, 'data': <HDF5 dataset "filtering": shape (32,), type "|O">}, 'group': root/general/extracellular_ephys/electrodes/group DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': 'dd41e056-2efa-4451-8a1a-1ad1a8f00aed'}, 'data': <hdmf.backends.hdf5.h5_utils.BuilderH5ReferenceDataset object at 0x7fc48779beb0>}, 'group_name': root/general/extracellular_ephys/electrodes/group_name DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': 'af516fae-a0f5-43a6-aa9e-501b9cb088ad'}, 'data': <HDF5 dataset "group_name": shape (32,), type "|O">}, 'id': root/general/extracellular_ephys/electrodes/id DatasetBuilder {'attributes': {'namespace': 'hdmf-common', 'neurodata_type': 'ElementIdentifiers', 'object_id': '52c8049a-d25b-4746-9099-d702d8931ebd'}, 'data': <HDF5 dataset "id": shape (32,), type "<i4">}, 'imp': root/general/extracellular_ephys/electrodes/imp DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': 'e2c78aa0-9835-4557-b0c4-c195f3c59464'}, 'data': <HDF5 dataset "imp": shape (32,), type "<f8">}, 'label': root/general/extracellular_ephys/electrodes/label DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '62479b54-d861-422e-a0f7-41396e0b44f7'}, 'data': <HDF5 dataset "label": shape (32,), type "|O">}, 'location': root/general/extracellular_ephys/electrodes/location DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': 'c04bb361-7498-4dd2-9689-5ea4ec0b13e4'}, 'data': <HDF5 dataset "location": shape (32,), type "|O">}, 'reference': root/general/extracellular_ephys/electrodes/reference DatasetBuilder {'attributes': {'namespace': 'hdmf-common'}, 'data': <HDF5 dataset "reference": shape (32,), type "|O">}, 'rel_x': root/general/extracellular_ephys/electrodes/rel_x DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '2e47f7cc-3d8a-48f5-ae15-9c4248774c8c'}, 'data': <HDF5 dataset "rel_x": shape (32,), type "<f8">}, 'rel_y': root/general/extracellular_ephys/electrodes/rel_y DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': 'd8a74312-db2f-4634-94e7-280b4873ddb9'}, 'data': <HDF5 dataset "rel_y": shape (32,), type "<f8">}, 'rel_z': root/general/extracellular_ephys/electrodes/rel_z DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '5d3818fa-d7f4-43fb-8f32-b9a622b17519'}, 'data': <HDF5 dataset "rel_z": shape (32,), type "<f8">}, 'x': root/general/extracellular_ephys/electrodes/x DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '4ab69eba-1271-4fb3-b289-894f2c3fba54'}, 'data': <HDF5 dataset "x": shape (32,), type "<f8">}, 'y': root/general/extracellular_ephys/electrodes/y DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '0d2093be-81b3-4b5c-941e-5b1a7f4dc68e'}, 'data': <HDF5 dataset "y": shape (32,), type "<f8">}, 'z': root/general/extracellular_ephys/electrodes/z DatasetBuilder {'attributes': {'description': 'my description', 'namespace': 'hdmf-common', 'neurodata_type': 'VectorData', 'object_id': '34f68914-6bdd-4cce-bd48-90fe932a2444'}, 'data': <HDF5 dataset "z": shape (32,), type "<f8">}}, 'links': {}}, "Could not construct DynamicTable object due to: 'reference'")
```

### Operating System

Linux

### Python Executable

Python

### Python Version

3.9

### Usage

Library (Python code)

### Were you streaming with ROS3?

Yes

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
As with the others, this steps from the fact that the file isn't readable, so we can pass the buck over to PyNWB if you agree @bendichter

**Comment by CodyCBakerPhD** [comment]
Going to call this a side-effect of #197 and hope that #223 fixes it. Will reopen if I encounter it again
