### ISSUE TITLE
[Bug]: inspect_all throws a pickle error

### ISSUE THREAD

**Issue by garrettmflynn** [NeurodataWithoutBorders/nwbinspector#415]
### What happened?

Running inspect_all throws a pickle error using the latest environment for the GUIDE.

## Traceback
```
Traceback (most recent call last):
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/apis/neuroconv.py", line 211, in post
    return inspect_multiple_filesystem_objects(paths)
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 613, in inspect_multiple_filesystem_objects
    result = inspect_nwb_folder({"path": tmp_folder_path})
  File "/Users/garrettflynn/Documents/Github/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 577, in inspect_nwb_folder
    messages = list(
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/site-packages/nwbinspector/nwbinspector.py", line 445, in inspect_all
    for message in future.result():
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/multiprocessing/queues.py", line 244, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/opt/anaconda3/envs/nwb-guide/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function auto_parse_some_output at 0x163072af0>: attribute lookup auto_parse_some_output on nwbinspector.register_checks failed
```

### Operating System

macOS

### Python Version

3.10

### Were you streaming with ROS3?

No

### Package Versions

[environment_for_issue.txt](https://github.com/NeurodataWithoutBorders/nwbinspector/files/13208370/environment_for_issue.txt)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
Can confirm this happens in my app as well, but the same usage via CLI on the same folder does not cause the same issue; will try direct API calls next

@garrettmflynn Does the standalone Inspector page do any of the usual symlink magic under the hood, or is it literally a direct call to the API endpoint with the target folder as the input?

**Comment by garrettmflynn** [comment]
For single folders and projects, this is the function used:
<img width="541" alt="Screenshot 2023-10-30 at 12 25 56 PM" src="https://github.com/NeurodataWithoutBorders/nwbinspector/assets/46533749/ab4f6720-2942-4d99-aad0-64ea725e7e7e">

**Comment by CodyCBakerPhD** [comment]
Just to help my side of debugging, is there anything else that would be in the `payload` object?

**Comment by garrettmflynn** [comment]
Aside from `path`, nothing else for now.

**Comment by CodyCBakerPhD** [comment]
Going to call this one 'done' as in, whatever approach we currently support for parallelization I hope we're testing it here. Otherwise we figured out the approach to take when using the API on the GUIDE side
