### ISSUE TITLE
[Documentation]: clarification to streaming with CLI with exact s3 path

### ISSUE THREAD

**Issue by stephprince** [NeurodataWithoutBorders/nwbinspector#479]
### What would you like changed or added to the documentation and why?

When walking through the User Guide, I saw this note in [Using the Command Line Interface (CLI): Streaming](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/5a8e910dc95bf192ab6ebfeb59293a292fa668cf/docs/user_guide/using_the_command_line_interface.rst?plain=1#L38C3-L38C4):

> You can also specify the exact S3 path instead of the DANDI set ID, if known. When specifying only the DANDI set ID, the S3 paths of all NWB assets are automatically fetched for your convenience.

When I try running: 

```bash
nwbinspector "https://dandiarchive.s3.amazonaws.com/blobs/11e/c89/11ec8933-1456-4942-922b-94e5878bb991" --stream
```

I get the error:
```python
Traceback (most recent call last):
  File "/Users/smprince/anaconda3/envs/nwbinspector2/bin/nwbinspector", line 8, in <module>
    sys.exit(inspect_all_cli())
             ^^^^^^^^^^^^^^^^^
  File "/Users/smprince/anaconda3/envs/nwbinspector2/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/anaconda3/envs/nwbinspector2/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/smprince/anaconda3/envs/nwbinspector2/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/anaconda3/envs/nwbinspector2/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/smprince/Documents/code/nwbinspector/src/nwbinspector/nwbinspector.py", line 275, in inspect_all_cli
    messages = list(
               ^^^^^
  File "/Users/smprince/Documents/code/nwbinspector/src/nwbinspector/nwbinspector.py", line 388, in inspect_all
    assert (
AssertionError: '--stream' flag was enabled, but 'path' is not a DANDISet ID.
```

From what I understand from the current docstring and assertion in `inspect_all`, only links to a dandiset are accepted.  I'm not sure if there's a different way to specify the exact s3 path or if it's best to remove this note / modify `inspect_all_cli` to accept s3 urls.

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
Good to know - we're planning on making the streaming aspect a completely separate function as well as removing the ROS3 in favor of remfile

So we'll be sure to tackle this along the way
